name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'
jobs:
  build:
    name: Create Release
    runs-on: windows-2022
    env:
      msbuildTargetZip: warppro-${{ github.ref_name }}-net45.zip
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
#       - name: Build the Docker image
#         run: docker build --file Dockerfile --tag dirkarnez/msbuild .
        
#         #run: docker build . --file Dockerfile --tag auycro/dotnet:$(date +%s)
        
#       - name: Run the Docker image
#         run: docker run --rm dirkarnez/msbuild --version
          
      - name: set PATH, check mingw version, cmake generate, build and install
        shell: cmd
        run: |
          set PATH=%PATH%;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin
          nuget restore .
          msbuild WarpPro.sln /p:Configuration=Release /p:Platform=x64
          dir /s
      
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "WarpPro/obj/x64/Release/net45"
          filename: "${{ env.msbuildTargetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "WarpPro/obj/x64/Release/net45/${{ env.msbuildTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
