name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on: [push]

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      libraryName: soundtouch
      cmakeInstallationPath: soundtouch-installation
      mingwTargetZip: soundtouch-${{ github.ref_name }}-mingw64-x86_64-posix-seh-rev0-8.1.0.zip
    steps:
      - name: git clone
        shell: cmd
        run: git clone --recursive https://github.com/xoascf/WarpPro.git
        
      - name: curl dotNetFx45_Full_setup.exe
        shell: cmd
        run: |
          curl https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-developer-pack-offline-installer -L --output C:\ndp48-devpack-enu.exe
          
      - shell: pwsh
        run: Start-Process -FilePath "C:\ndp48-devpack-enu.exe" -ArgumentList "/q /norestart" -Wait
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
          
      - name: set PATH, check mingw version, cmake generate, build and install
        shell: cmd
        run: |
          cd WarpPro &&^
          MSBuild.exe WarpPro.sln /p:Configuration=Release /p:Platform="x64"
      
      - uses: actions/upload-artifact@v2
        with:
          name: built-binaries
          path: bin\Debug
