name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on: [push]

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      libraryName: soundtouch
      cmakeInstallationPath: soundtouch-installation
      mingwTargetZip: soundtouch-${{ github.ref_name }}-mingw64-x86_64-posix-seh-rev0-8.1.0.zip
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build the Docker image
        run: docker build --file Dockerfile --tag dirkarnez/msbuild .
        
        #run: docker build . --file Dockerfile --tag auycro/dotnet:$(date +%s)
        
      - name: Run the Docker image
        run: docker run --rm dirkarnez/msbuild --version
          
      - name: set PATH, check mingw version, cmake generate, build and install
        shell: cmd
        run: |
          dir
      
      - uses: actions/upload-artifact@v2
        with:
          name: built-binaries
          path: bin/Debug
